const IS_PRESENT = 1, IS_PART_TIME = 2;
const EMP_RATE_PER_HR = 20;
const NUM_OF_WORKING_DAYS = 20;
const PART_TIME_HOURS = 4;
const FULL_TIME_HOURS = 8;
const MAX_HRS_IN_MONTH = 100;

module.exports = {IS_PRESENT,IS_PART_TIME,EMP_RATE_PER_HR,NUM_OF_WORKING_DAYS,FULL_TIME_HOURS,PART_TIME_HOURS,MAX_HRS_IN_MONTH}